---
- hosts: srv_lb
  become: yes
  tasks: 
    - name: Atualização do sistema
      apt: update_cache=yes cache_valid_time=3600
    
    - name: Instalação do HAproxy
      apt: name=haproxy state=present

    - name: Ativar script init
      replace: dest='/etc/default/haproxy' 
            regexp='ENABLED=0'
            replace='ENABLED=1'

    - name: Atualização das configurações
      template: src=templates/haproxy.cfg 
            dest=/etc/haproxy/haproxy.cfg 
            backup=yes
      notify: 
        - restart haproxy

    - name: Startar e habilitar o HAproxy no boot
      service: name=haproxy state=started enabled=yes
    
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted

 


